
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Author extends ContentItem {
    public personImage: Elements.AssetsElement;
    public personFirstName: Elements.TextElement;
    public eMailAddress: Elements.TextElement;
    public personLastName: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'person__image') {
                    return 'personImage';
                }
                if (elementName === 'person__first_name') {
                    return 'personFirstName';
                }
                if (elementName === 'e_mail_address') {
                    return 'eMailAddress';
                }
                if (elementName === 'person__last_name') {
                    return 'personLastName';
                }
                return elementName;
            })
        });
    }
}
