
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Chapter extends ContentItem {
    public title: Elements.TextElement;
    public shortSummary: Elements.RichTextElement;
    public body: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'short_summary') {
                    return 'shortSummary';
                }
                return elementName;
            })
        });
    }
}
