
import { ContentItem, Elements } from '@kentico/kontent-delivery';
import { Module01a2a1b } from './module_01a2a1b';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class CourseNew extends ContentItem {
    public title: Elements.TextElement;
    public shortSummary: Elements.RichTextElement;
    public modules: Elements.LinkedItemsElement<Module01a2a1b>;
    public headerImage: Elements.AssetsElement;
    public currency: Elements.TaxonomyElement;
    public price: Elements.NumberElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'short_summary') {
                    return 'shortSummary';
                }
                if (elementName === 'untitled_linked_items') {
                    return 'modules';
                }
                if (elementName === 'header_image') {
                    return 'headerImage';
                }
                if (elementName === 'price__usd_') {
                    return 'price';
                }
                return elementName;
            })
        });
    }
}
