
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class CustomerPersona extends ContentItem {
    public children: Elements.MultipleChoiceElement;
    public devices: Elements.MultipleChoiceElement;
    public job: Elements.TextElement;
    public drive: Elements.TextElement;
    public carModel: Elements.MultipleChoiceElement;
    public personality: Elements.RichTextElement;
    public companyCar: Elements.MultipleChoiceElement;
    public image: Elements.AssetsElement;
    public relationship: Elements.MultipleChoiceElement;
    public incomeLevel: Elements.MultipleChoiceElement;
    public location: Elements.TextElement;
    public worriesFears: Elements.RichTextElement;
    public hopes: Elements.RichTextElement;
    public quote: Elements.TextElement;
    public age: Elements.NumberElement;
    public hobbiesInterestsLifestyle: Elements.TextElement;
    public name: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'car_model') {
                    return 'carModel';
                }
                if (elementName === 'company_car_') {
                    return 'companyCar';
                }
                if (elementName === 'income_level') {
                    return 'incomeLevel';
                }
                if (elementName === 'worries___fears') {
                    return 'worriesFears';
                }
                if (elementName === 'hobbies__interests___lifestyle') {
                    return 'hobbiesInterestsLifestyle';
                }
                return elementName;
            })
        });
    }
}
